services:
  - type: web
    name: quotit-relay
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /relay/health
